src/objects/Car__c.object
<CustomObject>
    <description>Actuall Car</description>
    <fields>
        <fullName>Is_Valid_For_Rent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>defines if car is available for rent</description>
        <label>Is Valid For Rent</label>
        <type>Checkbox</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time
periods) and same car may have many deals made by various Sales
Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>SalesManager__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE( TODAY() )</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of rent.
Open (DEFAULT) - there is a cliend who called and asked
for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SalesManager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper
car.</description>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <description>Birth Date</description>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name</description>
        <label>Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Sales Manager</label>
    <nameField>
        <label>Sales Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CarRentServices.cls
public class CarRentServices {

    public static void setEndDate(Id recordId) {

        Deal__c d = [
                SELECT Id, End_Date__c
                FROM Deal__c
                WHERE Id = :recordId
        ];

        d.End_Date__c = Datetime.now();
        update d;

    }

    public static List<Deal__c> filterFinished() {

        List <Deal__c> deal = [
                SELECT Name__c
                FROM Deal__c
                ORDER BY Status__c
        ];

        return deal;

    }

    public static void createSalesManager(String name, Date birthdate) {

        SalesManager__c newSM = new SalesManager__c(Name = name, Birth_Date__c = birthdate);

        insert newSM;

    }

    public static void createNewDeal(Datetime startDate, Datetime endDate, Id salesRepId, Id carId) {

        Deal__c newDeal = new Deal__c(Start_Date__c = startDate, End_Date__c = endDate, Sales_Manager__c = salesRepId,
                Car__c = carId, Status__c = 'Open');

        insert newDeal;
    }


    public static void deactivateCar(Id carId) {
        List<Deal__c> dealsToUpdate = [
                SELECT Id, Status__c
                FROM Deal__c
                WHERE Car__c = :carId AND Status__c = 'Open'
        ];

        for (Deal__c deal : dealsToUpdate) {
            deal.Status__c = 'Lost';
        }
        update dealsToUpdate;
        System.debug(dealsToUpdate);

        Car__c brokenCar = [
                SELECT Id, Is_Valid_For_Rent__c
                FROM Car__c
                WHERE Id = :carId
        ];


            brokenCar.Is_Valid_For_Rent__c = false;
            update brokenCar;


    }

}