src/objects/Car__c.object
<CustomObject>
    <description>Actuall Car</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time
periods) and same car may have many deals made by various Sales
Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of rent.
Open (DEFAULT) - there is a cliend who called and asked
for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CarTriggerHandler.cls
/**
 * Created by 2lego on 20.12.2023.
 */

public with sharing class CarTriggerHandler {

    public static void updateOpenDealsWithBrokenCars(Map<Id, Car__c> carNewMap) {

        List <Deal__c> dealsWithBrokenCar = CarRentDAO.getOpenDealsWitchRelatedCars(carNewMap.keySet());

        if (!dealsWithBrokenCar.isEmpty()) {

            for (Deal__c d : dealsWithBrokenCar) {

                d.Status__c = 'Lost';

            }

                update dealsWithBrokenCar;


        }

    }

}