src/objects/Car__c.object
<CustomObject>
    <description>Actuall Car</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time
periods) and same car may have many deals made by various Sales
Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE( TODAY() )</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of rent.
Open (DEFAULT) - there is a cliend who called and asked
for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DealTriggerHandler.cls
/**
 * Created by 2lego on 25.12.2023.
 */

public with sharing class DealTriggerHandler {

    public static void setDateTodayForDeals(List <Deal__c> deals) {

        for (Deal__c record : deals) {

            if (record.Status__c == 'Won' || record.Status__c == 'Lost') {

                record.End_Date__c = System.today();
            }
        }
    }

    public static void preventDuplicatesWithSameTimePeriodAndStatusWonOrOpen(List<Deal__c> triggerNew) {
        Set<Id> cars = new Set<Id>();
        Set<Id> dealIds = new Set<Id>();
        for (Deal__c deal : triggerNew) {
            cars.add(deal.Car__c);
            dealIds.add(deal.Car__c);
        }
        List<Deal__c> queryDeals = [
                SELECT Car__c, Start_Date__c, End_Date__c, Status__c
                FROM Deal__c
                WHERE Car__c IN :cars
                AND (Status__c = 'Won' OR Status__c = 'Open')
                AND Id NOT IN :dealIds
        ];


        Map<Id, List<Deal__c>> dealMap = new Map<Id, List<Deal__c>>();
        for (Deal__c dealItem : queryDeals) {
            if (!dealMap.containsKey(dealItem.Car__c)) {
                dealMap.put(dealItem.Car__c, new List<Deal__c>());
            }
            dealMap.get(dealItem.Car__c).add(dealItem);
        }



        for (Deal__c deal : triggerNew) {
            if (dealMap.containsKey(deal.Car__c) && deal.Status__c == 'Open') {
                for (Deal__c dealItem : dealMap.get(deal.Car__c)) {
                    if (deal.Start_Date__c < dealItem.End_Date__c && deal.End_Date__c > dealItem.Start_Date__c) {
                        deal.addError('Duplicate deal with overlapping period found.');
                    }
                }
            }
        }
    }
}