src/objects/Car__c.object
<CustomObject>
    <description>Actuall Car</description>
    <fields>
        <fullName>Is_Valid_For_Rent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>defines if car is available for rent</description>
        <label>Is Valid For Rent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sedan</fullName>
                </value>
                <value>
                    <fullName>Minivan</fullName>
                </value>
                <value>
                    <fullName>Hatchback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time
periods) and same car may have many deals made by various Sales
Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>SalesManager__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE( TODAY() )</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of rent.
Open (DEFAULT) - there is a cliend who called and asked
for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SalesManager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper
car.</description>
    <label>Sales Manager</label>
    <nameField>
        <label>Sales Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCarTrigger.cls
@IsTest
private class TestCarTrigger {

    @IsTest
    static void testUpdateOpenDealsWithBrokenCars() {
        Car__c testCar = new Car__c(Name = 'Sedan', Type__c = 'Sedan', Is_Valid_For_Rent__c = true);
        insert testCar;
        System.debug(testCar);
        SalesManager__c manager = TestDataFactory.createSalesManager('TestName', true);

        Deal__c testDeal = new Deal__c
                (
                        Name = 'TestCarTriggerDeal',
                        Start_Date__c = Datetime.now().addDays(-1),
                        End_Date__c = Datetime.now(),
                        Sales_Manager__c = manager.Id,
                        Car__c = testCar.Id,
                        Status__c = 'Open'
                );
        insert testDeal;
        System.debug(testDeal);


        Test.startTest();
        testCar.Is_Valid_For_Rent__c = false;
        update testCar;
        System.debug(testCar);
        Test.stopTest();

        Deal__c resultDeal = [SELECT Status__c FROM Deal__c WHERE Id = :testDeal.Id];
        System.debug(resultDeal);
        Assert.areEqual('Lost', resultDeal.Status__c);
    }
}