src/objects/Car__c.object
<CustomObject>
    <description>Actuall Car</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time
periods) and same car may have many deals made by various Sales
Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>SalesManager__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE( TODAY() )</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of rent.
Open (DEFAULT) - there is a cliend who called and asked
for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SalesManager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper
car.</description>
    <label>Sales Manager</label>
    <nameField>
        <label>Sales Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDealTrigger.cls
/**
 * Created by 2lego on 23.12.2023.
 */

@IsTest
private class TestDealTrigger {
    @IsTest
    static void testPreventDuplicatesWithSameTimePeriodAndStatusWonOrOpen() {
        Car__c newCar = TestDataFactory.createNewCar('dealCar');
        Car__c newCar1 = TestDataFactory.createNewCar('dealCar1');
        SalesManager__c newSalesManager = TestDataFactory.createSalesManager('manager', true);
        SalesManager__c newSalesManager1 = TestDataFactory.createSalesManager('manager1', true);
        Deal__c newDeal = new Deal__c(Name = 'Test Name', Car__c = newCar.Id,
                Sales_Manager__c = newSalesManager.Id, Status__c = 'Open', Start_Date__c = Datetime.now().addDays(-1),
                End_Date__c = System.today().addDays(+1));
        Deal__c newDeal2 = new Deal__c(Name = 'Test Name', Car__c = newCar1.Id,
                Sales_Manager__c = newSalesManager1.Id, Status__c = 'Open', Start_Date__c = Datetime.now().addDays(-1),
                End_Date__c = System.today().addDays(+1));
        Deal__c newDeal3 = new Deal__c(Name = 'Test Name', Car__c = newCar1.Id,
                Sales_Manager__c = newSalesManager1.Id, Status__c = 'Open', Start_Date__c = Datetime.now().addDays(-1),
                End_Date__c = System.today().addDays(+1));
        Test.startTest();
        try {
            insert newDeal;
        } catch (Exception e) {
        } try {
            insert newDeal2;
        } catch (Exception e) {
        }
        try {
            insert newDeal3;
        } catch (Exception e) {
            System.debug('Cant create duplicate deal');
        }
        Test.stopTest();
    }

    @IsTest
    static void testSetDateTodayForDeals() {
        Car__c newCar = TestDataFactory.createNewCar('dealCar');
        SalesManager__c newSalesManager = TestDataFactory.createSalesManager('manager', true);
        Deal__c newDeal = new Deal__c(Name = 'Test Name', Car__c = newCar.Id,
                Sales_Manager__c = newSalesManager.Id, Status__c = 'Open', Start_Date__c = Datetime.now().addDays(-1),
                End_Date__c = System.today().addDays(+1));
        insert newDeal;

        Test.startTest();
        newDeal.Status__c = 'Lost';
        update newDeal;
        Test.stopTest();

        Deal__c endDate = [SELECT End_Date__c FROM Deal__c WHERE Id = :newDeal.Id];
        System.debug(endDate.End_Date__c);
        Assert.areEqual(endDate.End_Date__c.date(), Date.today());
    }


}