src/objects/Car__c.object
<CustomObject>
    <description>Actuall Car</description>
    <fields>
        <fullName>Is_Valid_For_Rent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>defines if car is available for rent</description>
        <label>Is Valid For Rent</label>
        <type>Checkbox</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time
periods) and same car may have many deals made by various Sales
Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>SalesManager__c</referenceTo>
        <relationshipLabel>Deal</relationshipLabel>
        <relationshipName>Deal</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE( TODAY() )</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of rent.
Open (DEFAULT) - there is a cliend who called and asked
for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SalesManager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper
car.</description>
    <label>Sales Manager</label>
    <nameField>
        <label>Sales Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    public static final Datetime SECOND_DAY = Datetime.now().addDays(1);
    public static final Datetime THIRD_DAY = Datetime.now().addDays(2);

    public static final Datetime START_DATE_TO_TEST_DEAL = Datetime.now().addDays(300);
    public static final Datetime END_DATE_TO_TEST_DEAL = Datetime.now().addDays(301);

        public static SalesManager__c createSalesManager(String managerName, Boolean isInsert) {
        SalesManager__c manager = new SalesManager__c(Name = managerName);
        if (isInsert) {
            insert manager;
        }
        return manager;
    }
    public static SalesManager__c createSalesManager(Boolean isInsert) {
        SalesManager__c manager = new SalesManager__c(Name = 'managerName');
        if (isInsert) {
            insert manager;
        }
        return manager;
    }

    public static Car__c createNewCar (String name){
        Car__c testCar = new Car__c(Name = name, Is_Valid_For_Rent__c = true);
        insert testCar;
        return testCar;
    }

    public static Deal__c createNewDealWithStatusOpen (String managerName, String carName){
        SalesManager__c testManager = createSalesManager(managerName,true);
                Car__c testCar1 = createNewCar(carName);


            Deal__c testOpenDeal = new Deal__c(
                    Name = 'Test Deal 1',
                    Car__c = testCar1.Id,
                    Sales_Manager__c = testManager.Id,
                    Start_Date__c = Datetime.now().addDays(2),
                    End_Date__c = Datetime.now().addDays(10),
                    Status__c = 'Open'
            );
            insert testOpenDeal;
            return testOpenDeal;
        }

    public static Deal__c createNewDealWithStatusWon (String managerName, String carName){
        SalesManager__c testManager = createSalesManager(managerName,true);
        Car__c testCar1 = createNewCar(carName);


        Deal__c newWonDeal = new Deal__c(
                Name = 'Test Deal 1',
                Car__c = testCar1.Id,
                Sales_Manager__c = testManager.Id,
                Start_Date__c = Datetime.now().addDays(-56),
                End_Date__c = Datetime.now(),
                Status__c = 'Open'
        );
        insert newWonDeal;
        System.debug('newWonDeal : ' + newWonDeal);
        System.debug('newWonDeal  s: ' + newWonDeal.Start_Date__c);
        System.debug('newWonDeal  d: ' + newWonDeal.End_Date__c);
        newWonDeal.Status__c = 'Won';
        update newWonDeal;
        return newWonDeal;
    }

    }